ktor {
  deployment {
    host = 0.0.0.0
    host = ${?HOST}
    port = 8080
    port = ${?PORT}
    maxChunkSize = 262144
  }

  application {
    modules = [ ru.meeweel.network_protocols_backend.ApplicationKt.module ]
  }
}

grpc {
  deployment {
    port = 9090
    port = ${?GRPC_PORT}
  }
}
